// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcav3-gS_FDG4HTO_Qr198Rs2kBApyHLA',
    appId: '1:581074559787:web:f8e9c70661968449961b6e',
    messagingSenderId: '581074559787',
    projectId: 'flutter-chat-app-4e33a',
    authDomain: 'flutter-chat-app-4e33a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e33a.appspot.com',
    measurementId: 'G-97RNS2MX9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LKDIh0Q7WGAJUCVmVUUxZmUSbTztMuM',
    appId: '1:581074559787:android:3eb8436d6f05dde6961b6e',
    messagingSenderId: '581074559787',
    projectId: 'flutter-chat-app-4e33a',
    storageBucket: 'flutter-chat-app-4e33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbOmROkVzBTA6TFKPKxVrBafRYyryBME',
    appId: '1:581074559787:ios:33e43f8fc0b123e0961b6e',
    messagingSenderId: '581074559787',
    projectId: 'flutter-chat-app-4e33a',
    storageBucket: 'flutter-chat-app-4e33a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLbOmROkVzBTA6TFKPKxVrBafRYyryBME',
    appId: '1:581074559787:ios:33e43f8fc0b123e0961b6e',
    messagingSenderId: '581074559787',
    projectId: 'flutter-chat-app-4e33a',
    storageBucket: 'flutter-chat-app-4e33a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcav3-gS_FDG4HTO_Qr198Rs2kBApyHLA',
    appId: '1:581074559787:web:b773476955e9a6c2961b6e',
    messagingSenderId: '581074559787',
    projectId: 'flutter-chat-app-4e33a',
    authDomain: 'flutter-chat-app-4e33a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e33a.appspot.com',
    measurementId: 'G-BQV82JM5D4',
  );
}
